meta_information: {
  probe_name: "{{ ansible_ssh_host }}",
  probe_location: "Umich",
  probe_foor: "bar"
}

schedules:
  - name: "schedule_every_1_min" 
    repeat: "*/1 * * * *"

BSSID_scans: 
  - name: "O_primary_BSSIDs"
    interface: "primary_network_interface"
    profiles: "all_profiles"
    unknown_SSID_warning: "true"
    schedule: [ "schedule_every_5_min" ]
    priority: 1
    meta_information: "probe_stats"

pssid_tasks: 
  - name: "example_task_override"
    profiles: ["O_MWireless_profile"]
    BSSIDs: "O_primary_BSSIDs"
    test: [ "O_example_test_rtt" ]
    archives: [ "O_example_rabbitmq_archive", "example_syslog_archive" ]
    schedule: [ "O_schedule_every_1_hour", "schedule_Tuesday_10:10AM" ]
    priority: 3
    ttl: 45
    meta_information: "probe_stats"
