meta_information:
  probe_ipv4: "{{ ansible_default_ipv4.address }}"
  probe_location: "Unknown"
  probe_name: "{{ ansible_default_ipv4.address }}"
  probe_id: "{{ ansible_default_ipv4.address }}"

pssid_tasks:
  - name: "task_rtt"
    profiles: ["MWireless_profile"]
    BSSIDs: "primary_BSSIDs"
    test: [ "test_rtt" ]
    archives: [ "rabbitmq_archive", "syslog_archive" ]
    schedule: [ "schedule_every_1_hour", "schedule_at_minute_30" ]
    priority: 3
    ttl: 45
    meta_information: "probe_stats"
  - name: "task_throughput"
    profiles: "WPA_encrypted_profiles"
    BSSIDs: "primary_BSSIDs"
    test: [ "test_throughput_ul", "test_throughput_dl" ]
    archives: [ "rabbitmq_archive", "syslog_archive" ]
    schedule:  [ "schedule_at_minute_10", "schedule_at_minute_40" ]
    priority: 2
    ttl: 120
    meta_information: "probe_stats"
    throughput_threshold: 95000000
  - name: "task_latency"
    profiles: "WPA_encrypted_profiles"
    BSSIDs: "primary_BSSIDs"
    test: [ "test_latency" ]
    archives: [ "rabbitmq_archive", "syslog_archive" ]
    schedule: [ "schedule_at_minute_20", "schedule_at_minute_50"]
    priority: 4
    ttl: 120
    meta_information: "probe_stats"
  - name: "task_http"
    profiles: "WPA_encrypted_profiles"
    BSSIDs: "primary_BSSIDs"
    test: [ "test_http_umich", "test_http_google" ]
    archives: [ "rabbitmq_archive", "syslog_archive" ]
    schedule: [ "schedule_every_1_hour", "schedule_at_minute_10"]
    priority: 5
    ttl: 120
    meta_information: "probe_stats"
  - name: "task_dns"
    profiles: "WPA_encrypted_profiles"
    BSSIDs: "primary_BSSIDs"
    test: [ "test_dns_a", "test_dns_aaaa" ]
    archives: [ "rabbitmq_archive", "syslog_archive" ]
    schedule: [ "schedule_every_1_hour", "schedule_at_minute_10"]
    priority: 6
    ttl: 120
    meta_information: "probe_stats"
