meta_information: {
  probe_name: "{{ ansible_default_ipv4.address }}",
  probe_location: "Umich",
  probe_foo: "bar"
}


BSSID_scans: 
  - name: "primary_BSSIDs"
    interface: "primary_network_interface"
    profiles: "all_profiles"
    unknown_SSID_warning: "true"
    schedule: [ "schedule_every_5_min" ]
    priority: 1
    meta_information: "probe_stats"

pssid_tasks: 
  - name: "example_task_override"
    profiles: ["MWireless_profile"]
    BSSIDs: "primary_BSSIDs"
    test: [ "example_test_rtt" ]
    archives: [ "example_rabbitmq_archive", "example_syslog_archive" ]
    schedule: [ "schedule_every_1_hour", "schedule_Tuesday_10:10AM" ]
    priority: 3
    ttl: 45
    meta_information: "probe_stats"
