# dhcp network setup using ifupdown and wpa_supplicant set up

- name: Uninstall netplan and setup network using ifupdown
  hosts:
    - pSSID-testpoints

  tasks:
    - name: create /etc/rc.local script
      file:
        path: /etc/rc.local
        state: touch
        mode: 0755

    
    - name: add commands to run after boot 
      blockinfile:
        path: /etc/rc.local
        insertafter: EOF
        marker: ""
        block: |
          #!/bin/sh
          set -e
          # TODO: Find what program pSSID needs to wait for after reboot, instead of sleeping
          sleep 120
          python3 /usr/local/bin/pssid/rpi_meta.py
          sleep 5
          ip link set wlan0 up
          python3 /usr/local/bin/pssid/pSSID.py /usr/local/bin/pssid/pssid_conf.json --debug> /home/pssid_output 2> /home/pssid_error
          exit 0
    
    
    - name: Remove blank lines from blockinfile
      lineinfile:
        path: /etc/rc.local
        state: absent
        regexp: '^$'


