# dhcp network setup using ifupdown and wpa_supplicant set up

- name: Uninstall netplan and setup network using ifupdown
  hosts:
    - pSSID-testpoints
  vars:
    - macaddress: "{{ ansible_default_ipv4.macaddress }}"
    - address: "{{ ansible_ssh_host }}"

  tasks:

    # - name: pause for 15 seconds
    #   pause:
    #     seconds: 15

#    - name: unmask, enable, restart networking
#      systemd:
#        name: networking
#        state: restarted
#        enabled: yes
#        masked: no


    - name: disable systemd-networkd.socket 
      systemd:
        name: systemd-networkd.socket
        state: stopped
        enabled: no
        masked: yes


    - name: disable systemd-networkd 
      systemd:
        name: systemd-networkd
        state: stopped
        enabled: no
        masked: yes


    - name: disable networkd-dispatcher 
      systemd:
        name: networkd-dispatcher
        state: stopped
        enabled: no
        masked: yes


    - name: disable systemd-networkd-wait-online
      systemd:
        name: systemd-networkd-wait-online
        state: stopped
        enabled: no
        masked: yes


    - name: bring up wireless interface
      command: ip link set wlan0 up


    - name: ensure localhost in in hosts file
      lineinfile:
        path: /etc/hosts
        regexp: '^127\.0\.0\.1'
        line: '127.0.0.1 localhost ubuntu'
        insertbefore: BOF

    - name: set dhclient connection timeout
      lineinfile:
        path: /etc/dhcp/dhclient.conf
        regexp: '^timeout'
        line: 'timeout 45;'

    - name: create wpa_supplicant
      file:
        path: "/etc/wpa_supplicant/wpa_supplicant_{{ item.SSID }}.conf"
        state: touch
      with_items: "{{ SSID_profiles }}"


    # SSID var is defined in the inventory
    - name: fill in basic info
      blockinfile:
        path: "/etc/wpa_supplicant/wpa_supplicant_{{ item.SSID }}.conf"
        block: |
          ctrl_interface=/var/run/wpa_supplicant
          update_config=1
          network={
              bssid=ADDRESS
              ssid={{item.SSID}}
              identity="{{item.identity}}"
              password={{item.password}}
              key_mgmt=WPA-EAP
          }
        insertbefore: BOF
      with_items: "{{ SSID_profiles }}"
      ignore_errors: yes


    # wpa conf for MSetup is different
    - name: fill in basic info for MSetup
      blockinfile:
        path: "/etc/wpa_supplicant/wpa_supplicant_MSetup.conf"
        block: |
          ctrl_interface=/var/run/wpa_supplicant
          update_config=1
          network={
              bssid=ADDRESS
              ssid="MSetup"
              key_mgmt=NONE
          }
        insertbefore: BOF

    - name: fill in basic info for MGuest
      blockinfile:
        path: "/etc/wpa_supplicant/wpa_supplicant_MGuest.conf"
        block: |
          ctrl_interface=/var/run/wpa_supplicant
          update_config=1
          network={
              bssid=ADDRESS
              ssid="MGuest"
              key_mgmt=NONE
          }
        insertbefore: BOF
