
- name: dhcp network setup
  hosts:
    - pSSID-testpoints
  vars:
    - macaddress: "{{ ansible_default_ipv4.macaddress }}"
    - address: "{{ ansible_ssh_host }}"
    - gateway: 198.111.224.145

  tasks:

    - name: disable dhcp
      lineinfile:
        path: /etc/netplan/50-cloud-init.yaml
        regexp: '^(.*)dhcp4'
        line: '            dhcp4: no'

    # XXX switch to proper variables
    # XXX need to add elastic route
    - name: add netplan config
      blockinfile:
        path: /etc/netplan/50-cloud-init.yaml
        insertafter: 'dhcp4: no'
        block: |
          # Ansible block
                      addresses: [{{ address }}/20]
                      gateway4: {{ gateway }}
                      nameservers:
                          addresses: [127.0.0.53, 8.8.8.8]
                      match:
                          macaddress: {{ macaddress }}
                      set-name: eth0
                      routes:
                      - to: 141.211.160.28
                        via: {{ gateway }} 

    - name: bring up wireless interface
      command: ip link set wlan0 up

    - name: ensure hostname in in hosts file
      lineinfile:
        path: /etc/hosts
        regexp: '^127\.0\.0\.1'
        line: '127.0.0.1 localhost ubuntu' 
        insertbefore: BOF

    - name: create wpa_supplicant
      file:
        path: /etc/wpa_supplicant/wpa_supplicant.conf
        state: touch

    # XXX pull wifi password from secerts file
    - name: fill in basic info
      blockinfile:
        path: /etc/wpa_supplicant/wpa_supplicant.conf
        block: |
          ctrl_interface=/var/run/wpa_supplicant
          update_config=1
          network={
              bssid=ADDRESS
              ssid=SSID_NAME
              identity="wifi-pi-test"
              password="redacted_pass"
              key_mgmt=WPA-EAP
          }
        insertbefore: BOF
