- name: extracting identifiers
  hosts:
    - pSSID-testpoints
  vars:
    - overwrite: False
    - machine_changed: True
    - warn: True
  tasks:
    
    - name: Serial Number 
      shell: 'cat /proc/cpuinfo | grep ^Serial | cut -d" " -f2' 
      register: serial_number

    - name: hardware Number 
      shell: 'cat /proc/cpuinfo | grep ^Hardware | cut -d" " -f2' 
      register: hardware_number
    
    
    - name: copy identifiers info to a local file
      blockinfile:
        block: |
          serial_number: "{{ serial_number.stdout }}"
          hardware_number: "{{ hardware_number.stdout }}"
          eth0.macaddress: "{{ ansible_eth0.macaddress }}"
          wlan0.macaddress: "{{ ansible_wlan0.macaddress }}"
        path: "{{ serial_directory }}/hardware_info"
        create: yes
      connection: local
      become: no
      delegate_to: localhost

    - name: dirs
      debug:
        msg: "{{ serial_directory }} and {{ probe_ids_directory }}"

    - name: copy meta info to a local file
      blockinfile:
        block: |
          meta_information: {{ meta_information | to_nice_json(indent=2) }}
        path: "{{ serial_directory }}/meta_info"
        create: yes
      connection: local
      become: no
      delegate_to: localhost


    - name: check if probe_id file exists
      stat:
        path: "{{ probe_ids_directory }}/README.md"
      register: stat_result
      connection: local
      become: no
      delegate_to: localhost

    - name: file content
      set_fact:
        val: "{{ lookup('file', '{{ probe_ids_directory }}/README.md') }}"
      when:  stat_result.stat.exists

    - name: checking if being run on the same machine
      set_fact:
        machine_changed: False 
        warn: False
      when:  stat_result.stat.exists and val is search(serial_number.stdout)

    - name: Warning
      debug:
        msg: "Directory for {{ meta_information.probe_id }} already exists"
      when: warn  

    #- name: Change overwrite 
    #  set_fact:
    #    overwrite: "yes"
    #  when: stat_result.stat.exists and machine_changed and con_overwrite.user_input and interactive 

    - name: End play
      meta: end_play
      when: warn and not overwrite | bool

    #- name: Create a directory if it does not exist
    #  file:
    #    path: "umich-pssid-info/probe_ids/{{ meta_information.probe_id }}"
    #    state: directory 
    #    mode: '0755'    
    #  connection: local
    #  become: no
    #  delegate_to: localhost

# Create README.md files
    - name: create README.md file with linked serial folder
      lineinfile:
        line: "https://github.com/UMNET-perfSONAR/umich-pssid-info/tree/main/serial/{{ serial_number.stdout }}"
        path: "{{ probe_ids_directory }}/README.md"
        regexp: '^https'
        create: yes
      connection: local
      become: no
      delegate_to: localhost

